FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

EXPOSE 8080
EXPOSE 8081

RUN apt-get update && \
    apt-get install -y iproute2 curl && \
    rm -rf /var/lib/apt/lists/*

USER app
COPY . .
ENTRYPOINT ["dotnet", "Example.Api.dll"]
